// libs/react-todos/src/lib/todo/todo.tsx
import { TodoWithRef } from '@nx-state-machine/machine';
import { useService } from '@xstate/react/lib';
import classNames from 'classnames';
import React, { ChangeEvent, KeyboardEvent, RefObject, useEffect, useRef } from 'react';

import './todo.css';

/* eslint-disable-next-line */
export interface TodoProps {
  todoRef: TodoWithRef['ref'];
}

export const Todo = ({ todoRef }: TodoProps) => {
  const [state, send] = useService(todoRef);
  const inputRef = useRef<HTMLInputElement>(null) as RefObject<HTMLInputElement>;
  const { id, title, completed } = state.context;

  useEffect(() => {
    todoRef.execute(state, {
      focusInput() {
        inputRef.current?.select();
      },
    });
  }, [state, todoRef]);

  const onTodoToggleChanged = () => {
    send('TOGGLE_COMPLETE');
  };

  const onLabelDoubleClicked = () => {
    send('EDIT');
  };

  const onDestroyClicked = () => {
    send('DELETE');
  };

  const onEditInputBlurred = () => {
    send('BLUR');
  };
  const onEditInputChanged = (event: ChangeEvent<HTMLInputElement>) => {
    send('CHANGE', { value: event.target.value });
  };
  const onEditInputKeyPressed = (event: KeyboardEvent) => {
    if (event.key === 'Enter') {
      send('COMMIT');
    }
  };
  const onEditInputKeyDown = (event: KeyboardEvent) => {
    if (event.key === 'Escape') {
      send('CANCEL');
    }
  };

  return (
    <li
      className={classNames({
        editing: state.matches('editing'),
        completed,
      })}
      key={id}
    >
      <div className="view">
        <input type="checkbox" className="toggle" onChange={onTodoToggleChanged} checked={completed} />
        <label onDoubleClick={onLabelDoubleClicked}>{title}</label>{' '}
        <button className="destroy" onClick={onDestroyClicked} />
      </div>
      <input
        type="text"
        className="edit"
        value={title}
        ref={inputRef}
        onBlur={onEditInputBlurred}
        onChange={onEditInputChanged}
        onKeyPress={onEditInputKeyPressed}
        onKeyDown={onEditInputKeyDown}
      />
    </li>
  );
};

export default Todo;

// libs/ng-todos/src/lib/todo/todo.component.ts
import {
  ChangeDetectionStrategy,
  ChangeDetectorRef,
  Component,
  ElementRef,
  Input,
  OnDestroy,
  OnInit,
  ViewChild,
} from '@angular/core';
import { TodoContext, TodoEvent, TodoStateSchema, TodoWithRef } from '@nx-state-machine/machine';
import { combineLatest, Observable, Subject } from 'rxjs';
import { map, takeUntil } from 'rxjs/operators';
import { State } from 'xstate';
import { TodoMachineService } from '../services/todo-machine.service';

interface TodoVm {
  context: TodoContext;
  isMatchEditing: boolean;
}

function toVm([state, context]: [State<TodoContext, TodoEvent, TodoStateSchema>, TodoContext]): TodoVm {
  const isMatchEditing = state.matches('editing');
  return { context, isMatchEditing };
}

@Component({
  selector: 'nx-state-machine-todo',
  templateUrl: './todo.component.html',
  styleUrls: ['./todo.component.css'],
  changeDetection: ChangeDetectionStrategy.OnPush,
  providers: [TodoMachineService],
})
export class TodoComponent implements OnInit, OnDestroy {
  @ViewChild('editInput') set editInput(value: ElementRef<HTMLInputElement>) {
    if (!value) {
      return;
    }

    this._editInput = value;
  }

  private _editInput: ElementRef<HTMLInputElement>;
  @Input() todoRef: TodoWithRef['ref'];

  vm$: Observable<TodoVm>;
  private destroy$ = new Subject<null>();

  constructor(private readonly _todoMachineService: TodoMachineService, private readonly _cdr: ChangeDetectorRef) {}

  ngOnInit(): void {
    this._todoMachineService.interpret(this.todoRef);
    this.vm$ = combineLatest([this._todoMachineService.state$, this._todoMachineService.stateContext$]).pipe(map(toVm));

    this._todoMachineService.state$.pipe(takeUntil(this.destroy$)).subscribe(state => {
      if (state.changed !== false && state.matches('editing')) {
        this._todoMachineService.execute(state, {
          focusInput: () => {
            requestAnimationFrame(() => this._editInput.nativeElement.select());
          },
        });
      }
    });
  }

  onToggled() {
    this._todoMachineService.sendEvent('TOGGLE_COMPLETE');
  }

  onLabelDoubleClicked() {
    this._todoMachineService.sendEvent('EDIT');
  }

  onDestroyClicked() {
    this._todoMachineService.sendEvent('DELETE');
  }

  onEditBlurred() {
    this._todoMachineService.sendEvent('BLUR');
  }

  onEditChanged(value: string) {
    this._todoMachineService.sendEvent('CHANGE', { value });
  }

  onEditEntered() {
    this._todoMachineService.sendEvent('COMMIT');
  }

  onEditEscaped() {
    this._todoMachineService.sendEvent('CANCEL');
  }

  ngOnDestroy(): void {
    this.destroy$.next();
  }
}

<li *ngIf="vm$ | async as vm" [ngClass]="{ completed: vm?.context.completed, editing: vm?.isMatchEditing }">
  <div class="view">
    <input
      type="checkbox"
      class="toggle"
      (change)="onToggled()"
      [checked]="vm?.context.completed"
      [value]="vm?.context.completed"
    />
    <label (dblclick)="onLabelDoubleClicked()">{{ vm?.context.title }}</label>
    <button class="destroy" (click)="onDestroyClicked()"></button>
  </div>
  <input
    #editInput
    type="text"
    class="edit"
    [value]="vm?.context.title"
    (blur)="onEditBlurred()"
    (change)="onEditChanged(editInput.value)"
    (keyup.enter)="onEditEntered()"
    (keyup.escape)="onEditEscaped()"
  />
</li>
