// libs/react-todos/src/lib/react-todos.tsx
import { TodosContext, TodosEvent, todosMachine } from '@nx-state-machine/machine';
import { useHashChange } from '@nx-state-machine/react-common';
import { useMachine } from '@xstate/react';
import classNames from 'classnames';
import React, { ChangeEvent, KeyboardEvent, useEffect } from 'react';
import Todo from './todo/todo';

const persistedTodosMachine = todosMachine.withConfig(
  {
    actions: {
      persist: context => {
        localStorage.setItem('todos-xstate-react', JSON.stringify(context.todos));
      },
    },
  },
  {
    newTodo: '',
    todos: (() => {
      try {
        return JSON.parse(localStorage.getItem('todos-xstate-react')) || [];
      } catch (e) {
        return [];
      }
    })(),
  },
);

export const ReactTodos = () => {
  const [state, send] = useMachine<TodosContext, TodosEvent>(persistedTodosMachine);

  useHashChange(({ newURL }) => {
    const currentFilter = newURL.split('#/').pop() || 'all';
    localStorage.setItem('todos-xstate-filter-react', currentFilter);
    send(`SHOW.${currentFilter}` as TodosEvent['type']);
  });

  useEffect(() => {
    send(`SHOW.${localStorage.getItem('todos-xstate-filter-react') || 'all'}` as TodosEvent['type']);
  });

  const { todos, newTodo } = state.context;

  const activeTodosCount = todos.filter(todo => !todo.completed).length;
  const isAllCompleted = todos.length > 0 && activeTodosCount === 0;
  const currentMark = !isAllCompleted ? 'completed' : 'active';
  const currentMarkEvent = `MARK.${currentMark}` as TodosEvent['type'];

  let filterTodos = todos;

  if (state.matches('active')) {
    filterTodos = todos.filter(todo => !todo.completed);
  } else if ((state as any).matches('completed')) {
    filterTodos = todos.filter(todo => todo.completed);
  }

  const onNewTodoKeyPressed = (event: KeyboardEvent<HTMLInputElement>) => {
    if (event.key === 'Enter') {
      send('NEWTODO.COMMIT');
    }
  };

  const onNewTodoChanged = (event: ChangeEvent<HTMLInputElement>) => {
    send('NEWTODO.CHANGE', { value: event.target.value });
  };

  const onToggleAll = () => {
    send(currentMarkEvent);
  };

  const onClearCompletedClicked = () => {
    send('CLEAR_COMPLETED');
  };

  return (
    <section className="todoapp">
      <header className="header">
        <h1>todos</h1>
        <input
          type="text"
          className="new-todo"
          placeholder={'What needs to be done?'}
          autoFocus
          onKeyPress={onNewTodoKeyPressed}
          onChange={onNewTodoChanged}
          value={newTodo}
        />
      </header>
      <section className="main">
        <input type="checkbox" className="toggle-all" id="toggle-all" checked={isAllCompleted} onChange={onToggleAll} />
        <label htmlFor="toggle-all" title={`Mark all as ${currentMark}`}>
          Mark all as {currentMark}
        </label>
        <ul className="todo-list">
          {filterTodos.map(todo => (
            <Todo key={todo.id} todoRef={todo.ref} />
          ))}
        </ul>
      </section>
      {!!todos.length && (
        <footer className="footer">
          <span className="todo-count">
            <strong>{activeTodosCount}</strong> item{activeTodosCount === 1 ? '' : 's'} left
          </span>
          <ul className="filters">
            <li>
              <a href="#/" className={classNames({ selected: state.matches('all') })}>
                All
              </a>
            </li>
            <li>
              <a href="#/active" className={classNames({ selected: state.matches('active') })}>
                Active
              </a>
            </li>
            <li>
              <a href="#/completed" className={classNames({ selected: state.matches('completed') })}>
                Completed
              </a>
            </li>
          </ul>
          {activeTodosCount < todos.length && (
            <button className="clear-completed" onClick={onClearCompletedClicked}>
              Clear Completed
            </button>
          )}
        </footer>
      )}
    </section>
  );
};

export default ReactTodos;

// libs/ng-todos/src/lib/todos/todos.component.ts
import { ChangeDetectionStrategy, Component, ElementRef, OnInit, ViewChild } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { TodosContext, TodosEvent, TodosStateSchema, TodoWithRef } from '@nx-state-machine/machine';
import { combineLatest, Observable, Subject } from 'rxjs';
import { map, takeUntil } from 'rxjs/operators';
import { State } from 'xstate';
import { TodosMachineService } from '../services/todos-machine.service';

interface TodosVm {
  context: TodosContext;
  isMatchAll: boolean;
  isMatchActive: boolean;
  isMatchCompleted: boolean;
  activeTodoCount: number;
  isAllCompleted: boolean;
  currentMark: string;
  currentMarkEvent: TodosEvent['type'];
  filteredTodos: TodoWithRef[];
}

function toVm([state, context]: [State<TodosContext, TodosEvent, TodosStateSchema>, TodosContext]): TodosVm {
  const isMatchAll = state.matches('all');
  const isMatchActive = state.matches('active');
  const isMatchCompleted = state.matches('completed');
  const activeTodoCount = context.todos.filter(todo => !todo.completed).length;
  const isAllCompleted = context.todos.length > 0 && activeTodoCount === 0;
  const currentMark = isAllCompleted ? 'active' : 'completed';
  const currentMarkEvent = `MARK.${currentMark}` as TodosEvent['type'];
  let filteredTodos = context.todos;

  if (state.matches('active')) {
    filteredTodos = context.todos.filter(todo => !todo.completed);
  } else if (state.matches('completed')) {
    filteredTodos = context.todos.filter(todo => todo.completed);
  }

  return {
    context,
    isMatchAll,
    isMatchActive,
    isMatchCompleted,
    activeTodoCount,
    currentMark,
    currentMarkEvent,
    filteredTodos,
    isAllCompleted,
  };
}

@Component({
  selector: 'nx-state-machine-todos',
  templateUrl: './todos.component.html',
  styleUrls: ['./todos.component.css'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class TodosComponent implements OnInit {
  @ViewChild('todoInput') set todoInput(value: ElementRef<HTMLInputElement>) {
    if (value) {
      value.nativeElement.focus();
    }
  }

  vm$: Observable<TodosVm>;

  private destroy$ = new Subject<null>();

  constructor(private readonly _todosMachineService: TodosMachineService, private readonly _route: ActivatedRoute) {}

  ngOnInit(): void {
    this._route.url
      .pipe(
        map(segments => {
          if (!segments.length) {
            return 'all';
          }

          return segments[0].path;
        }),
        takeUntil(this.destroy$),
      )
      .subscribe(path => {
        this._todosMachineService.sendEvent(`SHOW.${path}` as TodosEvent['type']);
      });

    this.vm$ = combineLatest([this._todosMachineService.state$, this._todosMachineService.stateContext$]).pipe(
      map(toVm),
    );
  }

  onNewTodoEntered() {
    this._todosMachineService.sendEvent('NEWTODO.COMMIT');
  }

  onNewTodoChanged(value: string) {
    this._todosMachineService.sendEvent('NEWTODO.CHANGE', { value });
  }

  onToggleAll(currentMarkEvent: TodosEvent['type']) {
    this._todosMachineService.sendEvent(currentMarkEvent);
  }

  onClearCompletedClicked() {
    this._todosMachineService.sendEvent('CLEAR_COMPLETED');
  }

  todosTrackByFn(index: number, item: TodoWithRef) {
    return item.id;
  }
}

<section class="todoapp" *ngIf="vm$ | async as vm">
  <header class="header">
    <h1>todos</h1>
    <input
      #todoInput
      type="text"
      class="new-todo"
      placeholder="What needs to be done?"
      [value]="vm.context.newTodo"
      (keyup.enter)="onNewTodoEntered()"
      (change)="onNewTodoChanged($any($event.target).value)"
    />
  </header>
  <section class="main">
    <input
      type="checkbox"
      class="toggle-all"
      id="toggle-all"
      [checked]="vm.isAllCompleted"
      (change)="onToggleAll(vm.currentMarkEvent)"
    />
    <label for="toggle-all" [title]="'Mark all as ' + vm.currentMark"> Mark all as {{ vm.currentMark }} </label>
    <ul class="todo-list">
      <nx-state-machine-todo
        *ngFor="let todo of vm.filteredTodos; trackBy: todosTrackByFn"
        [todoRef]="todo.ref"
      ></nx-state-machine-todo>
    </ul>
  </section>
  <ng-container *ngIf="!!vm.context.todos.length">
    <footer class="footer">
      <span class="todo-count">
        <strong>{{ vm.activeTodoCount }}</strong> item{{ vm.activeTodoCount === 1 ? '' : 's' }}
        left
      </span>
      <ul class="filters">
        <li>
          <a [routerLink]="['']" [ngClass]="{ selected: vm.isMatchAll }">All</a>
        </li>
        <li>
          <a [routerLink]="['', 'active']" [ngClass]="{ selected: vm.isMatchActive }">Active</a>
        </li>
        <li>
          <a [routerLink]="['', 'completed']" [ngClass]="{ selected: vm.isMatchCompleted }">Completed</a>
        </li>
      </ul>
      <button
        class="clear-completed"
        (click)="onClearCompletedClicked()"
        type="button"
        *ngIf="vm.activeTodoCount < vm.context.todos.length"
      >
        Clear Completed
      </button>
    </footer>
  </ng-container>
</section>
